version: '3'
services:
  api:
    build: ./services/api
    ports:
      - "8222:8222"

  certbot:
    image: certbot/certbot
    volumes:
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot

  web:
    build: ./
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
    volumes:
      - ./services/nginx:/etc/nginx/conf.d
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
